# This workflow will upload a Python Package using Twine when a release is created

name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build
    - name: Build
      run: python -m build
    - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6
      with:
        skip-existing: true
        verbose: true
        print-hash: true
        user: __token__
        password: ${{ secrets.PYPY_KEY }}
        repository-url: https://upload.pypi.org/legacy/
